name: CI

on: [ push, pull_request ]

  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '10', '12', '14' ]
    name: Unit Tests Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Units Tests
        run: npm run test:coverage